[versions]
agp = "8.5.2"
androidx_activity_compose = "1.9.1"
androidx_test = "1.6.1"
androidx_test_ext = "1.2.1"
appcompat = "1.7.0"
compile_sdk_version = "34"
compose-bom = "2024.06.00"
compose_compilerextension = "1.5.5"
constraint_layout = "2.1.4"
core_ktx = "1.13.1"
detekt = "1.23.6"
espresso_core = "3.6.1"
junit = "4.13.2"
kotlin = "1.9.20"
min_sdk_version = "23"
target_sdk_version = "34"
benmanesversion = "0.51.0"

[libraries]
junit = { module = "junit:junit", version.ref = "junit" }
androidx_activity_compose = { module = "androidx.activity:activity-compose", version.ref = "androidx_activity_compose" }
androidx_appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx_constraint_layout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraint.layout" }
androidx_core_ktx = { module = "androidx.core:core-ktx", version.ref = "core.ktx" }
androidx_test_rules = { module = "androidx.test:rules", version.ref = "androidx.test" }
androidx_test_runner = { module = "androidx.test:runner", version.ref = "androidx.test" }
androidx_test_ext_junit = { module = "androidx.test.ext:junit", version.ref = "androidx.test.ext" }
androidx_test_ext_junit_ktx = { module = "androidx.test.ext:junit-ktx", version.ref = "androidx.test.ext" }
compose-bom = { module = "androidx.compose:compose-bom", version.ref = "compose-bom" }
compose_material = { module = "androidx.compose.material:material" }
compose_foundation = { module = "androidx.compose.foundation:foundation" }
compose_ui = { module = "androidx.compose.ui:ui" }
compose_ui_tooling = { module = "androidx.compose.ui:ui-tooling" }
compose_ui_test_junit4 = { module = "androidx.compose.ui:ui-test-junit4" }
compose_ui_test_manifest = { module = "androidx.compose.ui:ui-test-manifest" }
detekt_formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }
espresso_core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso.core" }
agp = { module = "com.android.tools.build:gradle", version.ref = "agp" }
kgp = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version.ref = "detekt" }
versions = { id = "com.github.ben-manes.versions", version.ref = "benmanesversion" }